services:
  backend:
    image: webbylabhub/movies
    container_name: movies_backend
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./
      args:
        VITE_BACKEND_URL: "http://localhost:8000"

    container_name: movies_frontend
    ports:
      - "3000:80"
    environment:
      - API_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped
